In [1]:
from uatu.watchers import *
from sklearn.model_selection import train_test_split

/home/sean/.local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
X,Y = get_xy_from_dir('../data/Box000/', 0)

In [3]:
train_dset = Dataset(X[:6], Y[:6], 2, shuffle = True, augment = True)
test_dset = Dataset(X[6:8], Y[6:8], 2, shuffle = True, augment = True)

data = (train_dset, test_dset, None)

In [4]:
device = 'CPU:0'

In [5]:
X.shape

(64, 64, 64, 64, 1)

In [6]:
def convnet_init_fn(inputs, training=False):
    #TODO add more customization
    initializer = tf.variance_scaling_initializer(scale=2.0)
    # TODO gotta be a better way to do this?
    #prob = tf.cond(training, lambda : 0.5, lambda : 1.0) #should i do some fancier tf stuff?
    axis = -1
    # NOTE ask waren if i need separate relus
    conv1_out = tf.layers.conv3d(inputs, 2, kernel_size=16, padding='same')
    #                              kernel_initializer=initializer)
    bn1_out = tf.layers.batch_normalization(conv1_out, axis = axis, training=training)
    lr1_out = tf.nn.leaky_relu(bn1_out, alpha=0.01)
    ap1_out = tf.layers.average_pooling3d(lr1_out, pool_size=(31, 31, 31), strides = 2)
    
    flat_out = tf.layers.flatten(ap1_out)
    dense1_out = tf.layers.dense(flat_out, 256)# kernel_initializer=initializer)
    #drop1_out = tf.layers.dropout(dense1_out, training=training)
    lr7_out =  tf.nn.leaky_relu(dense1_out, alpha=0.01)

    dense2_out = tf.layers.dense(lr7_out, 2)# kernel_initializer=initializer)
    
    return dense2_out

In [7]:
train(convnet_init_fn, standard_optimizer_init_fn,data, device, fname = './shallow_test', num_epochs = 100)

Starting epoch 0
[[-0.12736118  0.15571979]
 [-0.18767244  0.17047149]]
[[0.28405  0.067711]
 [0.28405  0.067711]]
Iteration 0, loss = 1.0739
[[-366.3276   360.63544]
 [-367.04938  361.35846]] 
[[0.28405  0.067711]
 [0.28405  0.067711]]
******************************
()
[[ 18.169825  -13.5907545]
 [ 19.655758  -14.71944  ]]
[[0.28405  0.067711]
 [0.28405  0.067711]]
[[10.369879  -8.444642 ]
 [ 8.690333  -7.0867066]]
[[0.28405  0.067711]
 [0.28405  0.067711]]
Starting epoch 1
[[ 5.5337253 -4.3716393]
 [ 5.7478814 -4.5481353]]
[[0.28405  0.067711]
 [0.28405  0.067711]]
[[ 2.1576104 -1.6300125]
 [ 2.7663825 -2.162563 ]]
[[0.28405  0.067711]
 [0.28405  0.067711]]
[[-0.07484014  0.52149874]
 [-0.5479767   1.226086  ]]
[[0.28405  0.067711]
 [0.28405  0.067711]]
Starting epoch 2
[[0.09125972 0.8088664 ]
 [0.09434848 0.8324162 ]]
[[0.28405  0.067711]
 [0.28405  0.067711]]
[[0.620403   0.98397565]
 [0.60318434 1.0009223 ]]
[[0.28405  0.067711]
 [0.28405  0.067711]]
[[-0.19024093  0.11832096]
 [

[[ 0.217349   -0.00828558]
 [ 0.22113277 -0.00944716]]
[[0.28405  0.067711]
 [0.28405  0.067711]]
Iteration 70, loss = 0.2828
[[-28.714386    5.404019 ]
 [-28.923782    5.4887433]] 
[[0.28405  0.067711]
 [0.28405  0.067711]]
******************************
()
[[ 0.19950323  0.00290981]
 [ 0.1713114  -0.04179545]]
[[0.28405  0.067711]
 [0.28405  0.067711]]
Starting epoch 24
[[ 0.22127315  0.01979315]
 [ 0.18473051 -0.01799111]]
[[0.28405  0.067711]
 [0.28405  0.067711]]
[[0.27919653 0.07681462]
 [0.28958634 0.08374506]]
[[0.28405  0.067711]
 [0.28405  0.067711]]
[[0.3524836  0.15708145]
 [0.3108281  0.09806158]]
[[0.28405  0.067711]
 [0.28405  0.067711]]
Starting epoch 25
[[0.32693    0.11768881]
 [0.29364264 0.08289368]]
[[0.28405  0.067711]
 [0.28405  0.067711]]
[[0.25177494 0.04406847]
 [0.25852278 0.04767764]]
[[0.28405  0.067711]
 [0.28405  0.067711]]
[[0.269211   0.075306  ]
 [0.23627539 0.02474708]]
[[0.28405  0.067711]
 [0.28405  0.067711]]
Starting epoch 26
[[0.28738624 0.064363

KeyboardInterrupt: 